name: 自动同步上游NodeWarden源码
permissions:
  contents: write
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: 同步上游官方main分支
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          upstream_repository: shuaiplus/nodewarden
          upstream_branch: main
          target_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          sync_mode: fast-forward-only
          test_mode: false
